name: release

on:
  push:
    tags:
      - "v*"

jobs:
  nuget:
    name: Publish NuGet package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
          source-url: https://nuget.pkg.github.com/matigramirez/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: dotnet build ./src/Parsec
      - name: Create NuGet package
        run: dotnet pack ./src/Parsec --configuration Release

      - name: Publish NuGet package
        run: dotnet nuget push ./src/Parsec/bin/Release/*.nupkg
