name: nuget

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  nuget:
    name: Publish NuGet package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - run: dotnet build ./src/Parsec --configuration Release

      - name: Create NuGet package
        run: dotnet pack ./src/Parsec --configuration Release

      - name: Publish NuGet package
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
        run: dotnet nuget push ./src/Parsec/bin/Release/*.nupkg --api-key "$NUGET_AUTH_TOKEN" --source https://api.nuget.org/v3/index.json
