name: Create release and publish nuget package

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release for tag
        id: release_tag
        uses: Akryum/release-tag@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}

  nuget:
    name: Publish NuGet package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/matigramirez/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and generate NuGet package
        run: dotnet pack ./src/Parsec -c Release -o publish

      - name: Publish NuGet package
        run: dotnet nuget push ./publish/*.nupkg --skip-duplicate --no-symbols true
